### ISSUE TITLE
misidentifies encodings mid-stream

### ISSUE THREAD

**Issue by alexchandel** [runk/node-chardet#12]
When chardet is run on Buffer segments midstream, it misidentifies UTF-16LE as ISO-8859-1:

```js
...
let call = 0
var owrite = res.write
res.write = function (chunk, encoding, cb) {
  let enc = chardet.detect(chunk/*, { sampleSize: 32 }*/)
  console.log(`response: ${call} instanceof=${chunk.constructor.name} ${chunk.length} ${enc}`)
  call++
  owrite.apply(this, arguments)
}
...
```

(console output):

```
response: 0 instanceof=Buffer 65536 UTF-16LE
response: 1 instanceof=Buffer 65536 ISO-8859-1
response: 2 instanceof=Buffer 65536 ISO-8859-1
response: 3 instanceof=Buffer 14392 ISO-8859-1
```

Note the even length of the Buffer; UTF-16LE characters aren't split between buffers.

It's easy enough to save the identified encoding from the beginning of the stream, but still worth noting that Buffer without the BOM are misidentified, even though (in this case) every other byte is 0x00.

**Comment by runk** [comment]
Hey there. Can you share data for this test?
