### ISSUE TITLE
Replace use of `new Buffer()` (e.g. with `Buffer.alloc()`)

### ISSUE THREAD

**Issue by jacobq** [runk/node-chardet#18]
It looks like [here](https://github.com/runk/node-chardet/blob/v0.6.0/index.js#L100) and [here](https://github.com/runk/node-chardet/blob/v0.6.0/index.js#L114) this code is using `new Buffer()` to create a `Buffer` object. However, current versions of node have a newer API for this, and in 10.x one will see a deprecation warning like "[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.".

This affects downstream project as well, e.g. https://github.com/yarnpkg/yarn/issues/5477

**Comment by runk** [comment]
Fixed in v0.7.0
