### ISSUE TITLE
On windows, this detects utf8 as ISO-8859-2

### ISSUE THREAD

**Issue by nmors** [runk/node-chardet#3]
not much else here to say, apart from:

the source file was a csv enoded with UTF-8 using CRLF line endings: 

The following asssertion fails:
``` js
    const expected = "UTF-8"
    const actual = chardet.detectFileSync(models.sourceFilePath);

    assert(actual, expected)
    done();
```

**Comment by runk** [comment]
Can you share a file..?

**Comment by runk** [comment]
Closing as stale.
