### ISSUE TITLE
Add support for DOS/IBM codepages

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [runk/node-chardet#30]
For instance https://en.wikipedia.org/wiki/Code_page_850.

**Comment by osdiab** [comment]
Along with this would be nice to have EUC-CN.

Anyone have any good recommendations for alternatives to `chardet` that support more encodings? there is https://github.com/aadsm/jschardet, but it also looks pretty bundle-heavy.

**Comment by make-github-pseudonymous-again** [comment]
@runk Is this implemented or is this just closed to clean up the backlog?

**Comment by runk** [comment]
Closed due to age. If you're willing to contribute - please go ahead
