### ISSUE TITLE
Always error "in-browser"

### ISSUE THREAD

**Issue by GilgameshxZero** [runk/node-chardet#40]
Doesn't this recent comment for v1.3.0 just break the package in browser environments?
<https://github.com/runk/node-chardet/commit/3fe63a19aceb435e73acf21e8acd0f19e6666907>

Namely, doesn't this always throw an error when we try to run in-browser? Is this intended?

**Comment by runk** [comment]
Hey, can you be a bit more specific please? What's error? How do you run it, ways to reproduce etc?
