### ISSUE TITLE
`chardet` throws browser error in Electron

### ISSUE THREAD

**Issue by GilgameshxZero** [runk/node-chardet#44]
I opened a similar issue a while ago, but didn't have the time to follow-up then.

I'm working on resolving a bug in [museeks](https://github.com/martpie/museeks), an Electron application. The bug seems to be caused by `chardet` thinking that the Electron environment is a browser and thus throwing the "File system is not available" error via the "browser" redirect in `package.json`.

However, the Electron application is running on a desktop environment, and I'd like to keep using `chardet` for encoding detection if possible. I'm not sure what the best way to go about this is—it seems like there isn't an easy way to special-case Electron (hybrid) environments in configuration.

**Comment by martpie** [comment]
Not sure if it can help, but the target for the bundle for the UI of the electron app is Webpack's `electron-renderer` (and not `browser`).

https://webpack.js.org/configuration/target/#target

**Comment by runk** [comment]
I guess it means this magic spell does not do the trick: https://github.com/runk/node-chardet/blob/3fe63a19aceb435e73acf21e8acd0f19e6666907/package.json#L95

.. or another likely scenario is filesystem is really not available if you get this error from https://github.com/runk/node-chardet/blob/3fe63a19aceb435e73acf21e8acd0f19e6666907/src/fs/node.ts#L8

I'll try to reproduce this error to narrow down the issue.

**Comment by runk** [comment]
https://github.com/martpie/museeks/pull/562

**Comment by martpie** [comment]
Thank you so much for looking into it and even submitting a PR @runk 🙌 

@GilgameshxZero this can be closed

**Comment by GilgameshxZero** [comment]
Thanks for handling this @runk !
