### ISSUE TITLE
Large files can cause memory problems

### ISSUE THREAD

**Issue by atplack-tribridge** [runk/node-chardet#5]
First off, I like your approach.  I am processing large XML files and running out of memory.  I am using streams, but need to pass the encoding to the stream objects, so I need to pull the encoding synchronously prior to reading the file.

I have found that if I change the detectFileSync from using fs.readFileSync to using a smaller buffered read, this code runs faster and solves the problem.

module.exports.detectFileSync = function(filepath) {
  var buflen = 8096,
      fd = fs.openSync(filepath,'r'),
      buf = new Buffer(buflen);
  fs.readSync(fd, buf, 0, buflen);
  fs.closeSync(fd);
  return self.detect(buf);
}

Thank you.

**Comment by runk** [comment]
Solved in v0.4.0, check README file for example - look for `sampleSize`

**Comment by Githamza** [comment]
How can I use the DetectFile on uploaded-from-browser file with UNIT8Array type ?
