### ISSUE TITLE
Bundle

### ISSUE THREAD

**Issue by Sozialarchiv** [runk/node-chardet#75]
Is there a bundled version, that I can load in a browser? Or how can I produce it?

**Comment by runk** [comment]
May I understand it a little better, what is the use case? I.e. don't have bundler in your app/website and want a standalone library ?

**Comment by Sozialarchiv** [comment]
Thank you for your fast reply and your great software.

We are using the software in our iiif viewer: https://github.com/archival-IIIF/viewer

Here a demo: https://iiif-testing.sozialarchiv.ch/archivalIIIF?manifest=https://iiif-testing.sozialarchiv.ch/iiif/v3/manifest/encoding8859

It does a great job!

At the moment it is used by an import:
https://github.com/archival-IIIF/viewer/blob/master/src/viewer/plainText/PlainTextViewer.tsx#L6

We we thinking to make the use of chardet optional. Because it is not in every use case needed. 

So I thought it can be load by a separate script and the viewer checks if its available. Something like that:

<script type="text/javascript" src="chardet.min.js"></script>
<script type="text/javascript" src="archival-IIIF-viewer.min.js"></script>

So I wanted to ask if bundled version exists.

But if not, no problem. The bundled size of your software is anyway very small.

**Comment by runk** [comment]
Ah, I see. Unfortunately bundled version does not exist, however it should not be too hard to add it. I do not have much free time this week, but happy to accept a PR if you'd craft it. Otherwise can look into it in several days time
