### ISSUE TITLE
Failed to parse source map

### ISSUE THREAD

**Issue by Sozialarchiv** [runk/node-chardet#94]
I'm using chardet with react in the browser. I got the following compiling warning:

```
Failed to parse source map from '...\node_modules\chardet\src\encoding\ascii.ts' file: Error: ENOENT: no such file or directory, open '...\node_modules\chardet\src\encoding\ascii.ts'    
```

I checked the path and src is really not existing. Only a lib folder.

![grafik](https://github.com/runk/node-chardet/assets/17063042/1001063f-886f-42c8-856b-e047ee0e2676)

Nevertheless chardet is working.

**Comment by runk** [comment]
Not sure what version is it, but maps are definitely there: https://www.npmjs.com/package/chardet?activeTab=code

**Comment by Sozialarchiv** [comment]
It is version 2.0.0

I can confirm index.js.map is there.

Nevertheless  I got the error.

But it seems to be a react specific error:
https://stackoverflow.com/questions/63195843/webpack-module-warning-failed-to-parse-source-map-from-data-url

So you can let the issues closed.

Thank you very much.
